### ISSUE TITLE
npm run build must be runned two times for build

### ISSUE THREAD

**Issue by rhanka** [Swiftaff/rollup-plugin-iconify-svg#1]
I want to use this pretty wonderful lib with svelte.
I managed to use it in dev mode, but each time i add an icon, i have to trigger watch two time saving the code to update icons.js

When building first time, the build fails as there is no 'icons.js' on the first time (for example in automated build within Github Actions)

Perhaps just some docs missing ?

**Comment by Swiftaff** [comment]
Thanks @rhanka for your kind words and for submitting this issue - I hope you find the lib useful !
I confess not having tested as much as I should - but I have noticed the same issue with having to run watch multiple times, and the workaround I use is adding a delay to the watch, so that it doesn't reload until after the file is created. I'm not sure if there is a better way, e.g.
```
!production && livereload({ watch: "public", delay: 1000 }),
```
I will see if I can find a way around the missing icons.js on first load - but another workaround might be to just manually create the empty file?

**Comment by rhanka** [comment]
Thanx, that does the trick for live reload
