### ISSUE TITLE
Make README.md clear where to put icons.js (src or public)

### ISSUE THREAD

**Issue by rhanka** [Swiftaff/rollup-plugin-iconify-svg#2]
Hi,

Thanx for this usefull libs which now is used in https://deces.matchid.io (french death database).

It is unclear for me in the doc where to put icons.js : in public/ (as a result of build) or in src/ (so we have to commit it to work in prod).
I did the second way and commited icons.js as i didn't manage to make it automatically build on first time.

When migrating to 2.0.0, this methods seem to fail all the way (both in live dev mode with livereload, and on build time). I had to rollback to 1.0.3.

Would it be possible to make a doc on a full working example, choosing either public/ or src/ and making more clear if we need to commit the icon.js or if it will be generated on build time even on the first time, as needed on clean CI/CD pipelines as github action ?

Thank your for this usefull lib.

**Comment by Swiftaff** [comment]
Hi @rhanka - I saw your app - looks good, nice work!

I added some tests to this lib, but I wasn't able to replicate it failing on first build - although it has in the past for me. Do you have a simple way I could replicate that? If not I will take another look.

And I bumped the latest version to 2.0.0 to indicate there was a breaking API change.
Try using...
```
import icons from "./src/icons.js";
```
instead of...
```
import { icons } from "./src/icons.js";
```

You can find a simple example here:
https://github.com/Swiftaff/rollup-plugin-iconify-svg/tree/master/example.

So yes, you can just put the icons.js in src, since it will then be bundled along with the rest of the svelte app - e.g. you can see the icons.js has been included at the end of the bundle file here: https://github.com/Swiftaff/rollup-plugin-iconify-svg/blob/master/example/public/build/bundle.js#L324

But good idea, I will update the readme to make the API change, and the example clearer!

**Comment by Swiftaff** [comment]
Hi @rhanka - I have done some further tests with Github actions and CircleCI and I can only get it to fail on first build when using the older version. Please see previous comment, and do try 2.0.1 and let me know if you have any further issues.
